### ISSUE TITLE
Add-LogicMonitorWebsite

### ISSUE THREAD

**Issue by CalebBartle** [wetling23/logicmonitor-posh-module#10]
Wetling23,

I am trying to see if you have this function created, it appears the module only has function for creating website groups but no way to create a website, please let me know what I need to do to get this to work.

**Comment by wetling23** [comment]
I published 1.0.1.81 with Add-LogicMonitorWebsite.

**Comment by AndrewSav** [comment]
@wetling23 it is still missing from the export table in psd1, and thus inaccessible

**Comment by wetling23** [comment]
@AndrewSav, you were right. I published 1.0.2.10 (https://www.powershellgallery.com/packages/LogicMonitor/1.0.2.10) with the command. Sorry about that.
